package ar.edu.itba.game.backend.upgrades;

public enum UpgradeType {
	ANTIAIRCRAFT_UNIT_RESEARCH, FLYING_UNIT_RESEARCH, TOWER_ATTACK_RANGE_UPGRADE,
	TOWER_ATTACK_SPEED_UPGRADE, TOWER_DAMAGE_UPGRADE, UNIT_UPGRADE;
}
